### ISSUE TITLE
Can't build v8.3.0

### ISSUE THREAD

**Issue by kczx3** [josdejong/jsoneditor#1041]
We are using jsoneditor from tag v8.3.0 and the build script isn't working anymore.  This started within the last few weeks since my previous deployment of our application.

The log shows that webpack isn't creating the bundle or bundle-minimalist output and thus, the minify task can't find `/dist/jsoneditor.js`.

```
> Executing task: npm run build <


> jsoneditor@8.2.1 build /home/<user>/jsoneditor
> gulp

[14:53:33] Using gulpfile ~/jsoneditor/gulpfile.js
[14:53:33] Starting 'default'...
[14:53:33] Starting 'mkdir'...
[14:53:33] Finished 'mkdir' after 1.36 ms
[14:53:33] Starting 'embed-json-worker'...
[14:53:33] Finished 'embed-json-worker' after 1.7 ms
[14:53:33] Starting 'copy-img'...
[14:53:33] Starting 'copy-docs'...
[14:53:33] Starting 'bundle-css'...
[14:53:33] Copied images
[14:53:33] Finished 'copy-img' after 10 ms
[14:53:33] Copied doc
[14:53:33] Finished 'copy-docs' after 12 ms
[14:53:33] Finished 'bundle-css' after 19 ms
[14:53:33] Starting 'bundle'...
[14:53:33] Starting 'bundle-minimalist'...
[14:53:33] bundled jsoneditor.js
[14:53:33] Finished 'bundle' after 255 ms
[14:53:33] Starting 'minify'...
[14:53:33] 'minify' errored after 1.21 ms
[14:53:33] Error: ENOENT: no such file or directory, open '/home/<user>/jsoneditor/dist/jsoneditor.js'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at minify (/home/<user>/jsoneditor/gulpfile.js:97:26)
    at /home/<user>/jsoneditor/gulpfile.js:220:3
    at minify (/home/<user>/jsoneditor/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:426:14)
    at runBound (domain.js:439:12)
    at asyncRunner (/home/<user>/jsoneditor/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[14:53:33] 'default' errored after 285 ms
[14:53:33] The following tasks did not complete: <series>, bundle-minimalist
[14:53:33] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsoneditor@8.2.1 build: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsoneditor@8.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<user>/.npm/_logs/2020-07-08T18_53_33_753Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

Updating to the latest v9.0.3 seems to work but I'd like to try to understand what the issue is with the version we've been using.  It builds on my local Windows machine but our linux development node is what fails.

Any thoughts?

**Comment by josdejong** [comment]
If I understand you correctly, without changing the version number, suddenly the builds started to fail a few weeks ago? I really have no idea. Can it be related to upgrading to a newer version of Webpack or so? or having something broken in your node_modules?

**Comment by kczx3** [comment]
It appears to be related to https://github.com/babel/babel/issues/11615

It seems the gulp 'bundle' task (and others) are maybe not properly checking all necessary cases for issues.  See [Webpack's docs](https://webpack.js.org/api/node/#error-handling) on this matter.

If I run `npm update` and `npm audit fix` (actually had to run both of these in this order twice) it seems to build.  Others have commented on several Babel issues that they had to delete the whole package-lock.json and re-install dependencies.

**Comment by josdejong** [comment]
That sounds tricky. But if I understand you correctly the latest version of JSONEditor doesn't have this issue?

**Comment by kczx3** [comment]
Didn't seem to but that could be due to a slew of differences.

**Comment by kczx3** [comment]
I'll close this but also going to add the error seen in the stats parameter for the `webpackCompiler.run` callback for reference to others who may run into the same thing.

```
ModuleBuildError: Module build failed (from ./node_modules/babel-loader/lib/index.js):
      Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/<user>/jsoneditor/node_modules/@babel/helper-compilation-targets/package.json
          at applyExports (internal/modules/cjs/loader.js:491:9)
          at resolveExports (internal/modules/cjs/loader.js:507:23)
          at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
          at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
          at Function.Module._load (internal/modules/cjs/loader.js:842:27)
          at Module.require (internal/modules/cjs/loader.js:1026:19)
          at require (internal/modules/cjs/helpers.js:72:18)
          at Object.<anonymous> (/home/<user>/jsoneditor/node_modules/@babel/preset-env/lib/debug.js:8:33)
          at Module._compile (internal/modules/cjs/loader.js:1138:30)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
          at /home/<user>/jsoneditor/node_modules/webpack/lib/NormalModule.js:316:20
          at /home/<user>/jsoneditor/node_modules/loader-runner/lib/LoaderRunner.js:367:11
          at /home/<user>/jsoneditor/node_modules/loader-runner/lib/LoaderRunner.js:233:18
          at context.callback (/home/<user>/jsoneditor/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
          at /home/<user>/jsoneditor/node_modules/babel-loader/lib/index.js:55:103
    ]
```
