### ISSUE TITLE
SyntaxError: Unexpected token: keyword «const» when build

### ISSUE THREAD

**Issue by xkungfu** [josdejong/jsoneditor#1121]
v9.1.1 
npm run build failed when minifying file "minify-minimalist".
error log:
'minify-minimalist' errored 
SyntaxError: Unexpected token: keyword «const»

after investigate , I think it is related UglifyJs and es6 and so on,  and the error function is in gulpfile.js :

caused by "uglify.minify".

but I am a newbie for this. I can't resove it myself.
Can you give me some suggestions?
and,
why other users didn't report this error?
did I miss something on the docs?

**Comment by josdejong** [comment]
I'm not sure I fully understand what you're doing, how can I reproduce this issue?

**Comment by xkungfu** [comment]
thank you.
please open the gulpfile.js file of version 9.1.1.
the line 103:

`  const result = uglify.minify(code, {`

here call uglify-js's minify method.

when execute "npm run build", error throwed by this function. the error said:
"SyntaxError: Unexpected token: keyword «const» "

Did I express it clearly?

**Comment by josdejong** [comment]
When I clone the project from github, run `npm install`, then run `npm run build`, I do not get this error. What version of node.js are you using?

**Comment by xkungfu** [comment]
$ npm run build

error log:

```

> jsoneditor@9.1.1 build /npmroot/josdejong-jsoneditor/node_modules/jsoneditor
> gulp

[04:30:24] Using gulpfile /npmroot/josdejong-jsoneditor/node_modules/jsoneditor/gulpfile.js
[04:30:24] Starting 'default'...
[04:30:24] Starting 'mkdir'...
[04:30:24] Finished 'mkdir' after 942 μs
[04:30:24] Starting 'embed-json-worker'...
[04:30:24] Finished 'embed-json-worker' after 775 μs
[04:30:24] Starting 'copy-img'...
[04:30:24] Starting 'copy-docs'...
[04:30:24] Starting 'bundle-css'...
[04:30:24] Copied images
[04:30:24] Finished 'copy-img' after 6.23 ms
[04:30:24] Copied doc
[04:30:24] Finished 'copy-docs' after 7.22 ms
[04:30:24] Finished 'bundle-css' after 10 ms
[04:30:24] Starting 'bundle'...
[04:30:24] Starting 'bundle-minimalist'...
[04:30:26] bundled jsoneditor-minimalist.js
[04:30:26] Finished 'bundle-minimalist' after 2.41 s
[04:30:26] Starting 'minify-minimalist'...
[04:30:26] 'minify-minimalist' errored after 24 ms
[04:30:26] SyntaxError: Unexpected token: keyword «const»
    at JS_Parse_Error.get (eval at <anonymous> (/npmroot/josdejong-jsoneditor/node_modules/jsoneditor/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:69:23)
    at formatError (/npmroot/josdejong-jsoneditor/node_modules/jsoneditor/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:17:20)
    at Gulp.<anonymous> (/npmroot/josdejong-jsoneditor/node_modules/jsoneditor/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (events.js:327:22)
    at Gulp.EventEmitter.emit (domain.js:483:12)
    at Object.error (/npmroot/josdejong-jsoneditor/node_modules/jsoneditor/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/npmroot/josdejong-jsoneditor/node_modules/jsoneditor/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/npmroot/josdejong-jsoneditor/node_modules/jsoneditor/node_modules/once/once.js:25:25)
    at f (/npmroot/josdejong-jsoneditor/node_modules/jsoneditor/node_modules/once/once.js:25:25)
    at tryCatch (/npmroot/josdejong-jsoneditor/node_modules/jsoneditor/node_modules/async-done/index.js:24:15)
[04:30:26] 'default' errored after 2.45 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsoneditor@9.1.1 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsoneditor@9.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-09-30T20_30_26_552Z-debug.log

```

**Comment by xkungfu** [comment]
I didn't clone by git.
I download release package version 9.1.1

then:
$: cd /npmroot/josdejong-jsoneditor
$: npm install jsoneditor

then:
$: cd  /npmroot/josdejong-jsoneditor/node_modules/jsoneditor

at this time, I copy gulpfile.js from release package version 9.1.1 to /npmroot/josdejong-jsoneditor/node_modules/jsoneditor

and then:
$: npm install
$: npm run build

that is all.

then the error occurred!

my nodejs version is :v12.18.3

**Comment by xkungfu** [comment]
I tried reinstall by the steps you said.

use "git clone", not "npm",

and all files are generated successfully .now all works like a charm.

the issue resovled!

maybe there is something wrong in the release package.

thank you very much.

**Comment by josdejong** [comment]
Great to hear it's working now. 

So I think you installed via `npm install jsoneditor`, and tried to build what was downloaded from npm? That is not needed or even possible in most cases: npm contains the build stuff, ready to use, and no need to build it. And github contains the source code, which you can build (and after that publish on npm).
