### ISSUE TITLE
Failing to build within NextJS project

### ISSUE THREAD

**Issue by sergiuchuckmisha** [josdejong/jsoneditor#1433]
Hello, I was super excited to see this project. I've been using the original version within my project and it does have it quarks. My steps for repo:

use a nextJS project (npx create-next-app)
npm install jsoneditor
copy files (without .css) from /examples/react_demo into nextJS project
run 'npm run build'

Errors:

```
ReferenceError: self is not defined
    at Object.<anonymous> (/home/misha/IdeaProjects/tmp/next-hw/node_modules/jsoneditor/dist/jsoneditor.min.js:30:202)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.654 (/home/misha/IdeaProjects/tmp/next-hw/.next/server/pages/index.js:52:45)
    at __webpack_require__ (/home/misha/IdeaProjects/tmp/next-hw/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/misha/IdeaProjects/tmp/next-hw/.next/server/pages/index.js:345:39) {
  type: 'ReferenceError'
}
```

Have a suspicion that this is due to server-side-rendering.

**Comment by josdejong** [comment]
Thanks for reporting. Sounds indeed like a server side rendering issue. 

I haven't used NextJS myself so far but I suppose it is possible to configure whether or not to render a specific page server side?

**Comment by NotsayJustdo** [comment]
# The question is due to ssr in Nextjs, you can use the dynamic/lazy import to solve this problem.
```
// ./Demo.tsx

import { useState, useRef } from 'react'
import JSONEditor from 'jsoneditor';
import 'jsoneditor/dist/jsoneditor.css';

let jsonEditor: any = null;
export default function Demo() {
  const editorRef = useRef<HTMLDivElement>(null);
  const { value } = props;
  useEffect(() => {
    const options = {
      mode: 'code',
      onChangeJSON: (e) => console.log(e),
    };
    jsonEditor = new JSONEditor(editorRef.current, options);
    jsonEditor.set({ "a": "1", "b": "2" });

    return () => {
      jsonEditor.destroy();
    };
  }, [value]);

  return <div className="jsoneditor-react-container" ref={editorRef} />;
}

```
```
// ./App.tsx

import dynamic from 'next/dynamic';

const Demo = dynamic(() => import('./Demo'), { ssr: false })
```

**Comment by josdejong** [comment]
Thanks for sharing the lazy import solution @NotsayJustdo  👍 

I'll close this issue now.
