### ISSUE TITLE
remix example?

### ISSUE THREAD

**Issue by jb44** [josdejong/jsoneditor#1461]
I'm trying to integrate this with my Remix app and am running into an issue . . .

```
import {useEffect, useState, useRef} from "react";
import JSONEditor from 'jsoneditor';
import type { LinksFunction } from "@remix-run/node";
import stylesUrl from 'jsoneditor/dist/jsoneditor.css';

export const links: LinksFunction = () => {
    return [{ rel: "stylesheet", href: stylesUrl }];
};

let jsonEditor: any = null;

export default function EditorRoute() {
    const editorRef = useRef<HTMLDivElement>(null);
    const value = "test";

    useEffect(() => {
        const options = {
            mode: 'code',
            onChangeJSON: (e:any) => console.log(e),
        };
        jsonEditor = new JSONEditor(editorRef.current, options);
        jsonEditor.set({ "a": "1", "b": "2" });

        return () => {
            jsonEditor.destroy();
        };
    }, [value]);

    return (
        <div className="jsoneditor-react-container" ref={editorRef} />
    )
}
```

Results in:

```
ReferenceError: self is not defined
    at Object.<anonymous> (C:\Users\xxx\code\remix\remix-jokes\node_modules\jsoneditor\dist\0:31:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\jboorn\code\remix\remix-jokes\app\routes\editor.tsx:2:38)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

I also tried using this:
Then I tried this package: https://www.npmjs.com/package/jsoneditor-react

But I get:

```
import React, { Component } from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\jboorn\code\remix\remix-jokes\app\routes\editor.tsx:2:38)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

Ideas/example of this working in Remix?

Thanks

**Comment by josdejong** [comment]
I do not understand `\node_modules\jsoneditor\dist\0:31:1` in the stacktrace, it should end with a file name.

Can you try to import like `import JSONEditor from 'jsoneditor/dist/jsoneditor.min.js';` ?

**Comment by jb44** [comment]
I swapped out the line:
`import JSONEditor from 'jsoneditor';`

with the line:
`import JSONEditor from 'jsoneditor/dist/jsoneditor.min.js'`

and received the same error:
```
ReferenceError: self is not defined
    at Object.<anonymous> (C:\Users\xxx\code\remix\remix-jokes\node_modules\jsoneditor\dist\0:31:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\jboorn\code\remix\remix-jokes\app\routes\editor.tsx:2:24)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

```

**Comment by jb44** [comment]
My sense is that this is related to the SSR rendering in remix (and possibly dynamic loading of ES modules).  I've read a few of the posts relating to this issue but none of them seem to offer a suggestion that works.

**Comment by josdejong** [comment]
I have no clue honestly, I have no experience with Remix. 

I do know that JSONEditor only works in the browser, not server side. If you can turn off SSR somehow that may solve it.

**Comment by jb44** [comment]
Ok - I used some remix add-ons to sidestep the server side rendering and load the script as an external resource:

```
let scripts: ExternalScriptsFunction = () => {
    return [
        {
            src: "https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.9.0/jsoneditor.min.js",
            crossOrigin: "anonymous",
        },
    ];
};

```

Which seems to do the trick.

Thanks so much for the prompt reply here!  Very helpful.
