### ISSUE TITLE
Getting the error sometimes while typing fast in the jsoneditor.

### ISSUE THREAD

**Issue by Laxmikantw** [josdejong/jsoneditor#1540]
**While typing in the jsoneditor little bit faster, then some times getting below error.** 

ERROR
Cannot read properties of null (reading 'getInternalPath')
TypeError: Cannot read properties of null (reading 'getInternalPath')
    at x.value (http://localhost:3000/static/js/bundle.js:32690:41)
    at http://localhost:3000/static/js/bundle.js:35440:30
    
    
**Is there any way or any function which can call at the end of typing?**

**Comment by josdejong** [comment]
Thanks for reporting @Laxmikantw .

How can I reproduce this issue? I picked one of the built in examples but didn't manage to reproduce this when fast typing.

The editor has a debouncing mechanism that is used whilst typing, that may have to do with it?
